@API_URL = http://localhost:3000/pms/api/v1 
# @API_URL = http://192.168.1.160:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjMyODIsIkVtcElkIjoiY3dsMi13YXNoLWNoZWNrIiwiVXNlck5hbWUiOiJjd2wyLXdhc2gtY2hlY2siLCJUeXBlTmFtZSI6Ildhc2hDaGVja2luZyIsIkNvbXBhbnlJZCI6MTcsIlVuaXRJZCI6Ijg3IiwiRnVsbE5hbWUiOiJjd2wyLXdhc2gtY2hlY2siLCJMaW5lSWQiOm51bGwsIklzU2V3aW5nIjpudWxsLCJJc1dhc2hpbmciOnRydWUsIklzRmluaXNoaW5nIjpudWxsLCJVc2VyVHlwZSI6Ildhc2hDaGVja2luZyIsImlhdCI6MTY5Njk5MDg0NX0.2ue1t0EOod9y5BWOBFB-_Ufw4o9-5qbyhlOChLBVC5w

###
POST {{API_URL}}/check/checking
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "challan_id": "86",
    "checking_type": "WashChecking"
}

###
POST {{API_URL}}/check/checking-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "checking_type": "FinishingChecking",
    "list_type":"waiting"
}

###
POST {{API_URL}}/check/summary
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "checking_type": "WashChecking",
    "challan_id":98
}



