@API_URL = http://localhost:3000/pms/api/v1 
# @API_URL = http://192.168.1.160:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjMyODMsIkVtcElkIjoiY2NsMWEtZmluaXNoaW5nLWNoZWNrIiwiVXNlck5hbWUiOiJjY2wxYS1maW5pc2hpbmctY2hlY2siLCJVbml0TmFtZSI6IkNDTCBVbml0IDFBIChUSUdMKSIsIlVzZXJUeXBlIjoiRmluaXNoaW5nIiwiVHlwZU5hbWUiOiJGaW5pc2hpbmdDaGVja2luZyIsIkNvbXBhbnlJZCI6MTIsIlVuaXRJZCI6IjciLCJGdWxsTmFtZSI6ImNjbDFhLWZpbmlzaGluZy1jaGVjayIsIkxpbmVJZCI6bnVsbCwiSXNTZXdpbmciOm51bGwsIklzV2FzaGluZyI6bnVsbCwiSXNGaW5pc2hpbmciOnRydWUsImlhdCI6MTY5OTQxNDgyM30.lFJh8OZQZ7-ikeNXu-mMUCefWYH9fIpPPtMV4lvXl3s

###
POST {{API_URL}}/check/checking
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "challan_id": "86",
    "checking_type": "WashChecking"
}

###
POST {{API_URL}}/check/checking-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "checking_type": "FinishingChecking",
    "list_type":"waiting"
}

###
POST {{API_URL}}/check/summary
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "checking_type": "FinishingChecking",
    "challan_id":15
}



