@API_URL = http://localhost:3000/pms/api/v1 
# @API_URL = http://192.168.1.160:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjMyODIsIkVtcElkIjoiY3dsMS13YXNoLWNoZWNrIiwiVXNlck5hbWUiOiJjd2wxLXdhc2gtY2hlY2siLCJVbml0TmFtZSI6IkNXTCBVbml0IDAxIiwiVXNlclR5cGUiOiJXYXNoaW5nIiwiVHlwZU5hbWUiOiJXYXNoQ2hlY2tpbmciLCJDb21wYW55SWQiOjE3LCJVbml0SWQiOiI4NyIsIkZ1bGxOYW1lIjoiY3dsMS13YXNoLWNoZWNrIiwiTGluZUlkIjpudWxsLCJJc1Nld2luZyI6bnVsbCwiSXNXYXNoaW5nIjp0cnVlLCJJc0ZpbmlzaGluZyI6bnVsbCwiaWF0IjoxNzAwNDgxOTgzfQ.0rEgzw-96ft-N2owIi9SUIAGPKwU-VQDGwNeUPmPDDI

###
POST {{API_URL}}/check/checking
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "challan_id": "86",
    "checking_type": "WashChecking"
}

###
POST {{API_URL}}/check/checking-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "checking_type": "WashChecking",
    "list_type":"waiting",
    "is_return":true
}

###
POST {{API_URL}}/check/summary
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "checking_type": "FinishingChecking",
    "challan_id":2,
    "is_return":true
}



