@API_URL = http://localhost:3000/pms/api/v1 
# @API_URL = http://192.168.1.160:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjMyODIsIkVtcElkIjoiY3dsMi13YXNoLWNoZWNrIiwiVXNlck5hbWUiOiJjd2wyLXdhc2gtY2hlY2siLCJUeXBlTmFtZSI6Ildhc2hDaGVja2luZyIsIkNvbXBhbnlJZCI6MTcsIlVuaXRJZCI6Ijg3IiwiRnVsbE5hbWUiOiJjd2wyLXdhc2gtY2hlY2siLCJMaW5lSWQiOm51bGwsIklzU2V3aW5nIjpudWxsLCJJc1dhc2hpbmciOnRydWUsIklzRmluaXNoaW5nIjpudWxsLCJVc2VyVHlwZSI6Ildhc2hDaGVja2luZyIsImlhdCI6MTY5Njk5MDg0NX0.2ue1t0EOod9y5BWOBFB-_Ufw4o9-5qbyhlOChLBVC5w


###
GET {{API_URL}}/finishing-dashboard/all
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}

###
GET {{API_URL}}/finishing-dashboard/total-received?unitId=7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}


###
GET {{API_URL}}/finishing-dashboard/rejection-percentage?unitId=7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}

###
GET {{API_URL}}/finishing-dashboard/total-production?unitId=7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}

###
GET {{API_URL}}/finishing-dashboard/this-month-total-production?unitId=7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}

###
GET {{API_URL}}/finishing-dashboard/wip?unitId=7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}
###
GET {{API_URL}}/finishing-dashboard/weekly-receive-vs-production?unitId=7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}
###
GET {{API_URL}}/finishing-dashboard/line-wise-target-production-dhu?unitId=7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}
###
GET {{API_URL}}/finishing-dashboard/achievement?unitId=7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}





