@API_URL = http://localhost:3000/pms/api/v1 
# @API_URL = http://192.168.1.160:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjMyODMsIkVtcElkIjoiY2NsMWEtZmluaXNoaW5nLWNoZWNrIiwiVXNlck5hbWUiOiJjY2wxYS1maW5pc2hpbmctY2hlY2siLCJVbml0TmFtZSI6IkNDTCBVbml0IDFBIChUSUdMKSIsIlVzZXJUeXBlIjoiRmluaXNoaW5nIiwiVHlwZU5hbWUiOiJGaW5pc2hpbmdDaGVja2luZyIsIkNvbXBhbnlJZCI6MTIsIlVuaXRJZCI6IjciLCJGdWxsTmFtZSI6ImNjbDFhLWZpbmlzaGluZy1jaGVjayIsIkxpbmVJZCI6bnVsbCwiSXNTZXdpbmciOm51bGwsIklzV2FzaGluZyI6bnVsbCwiSXNGaW5pc2hpbmciOnRydWUsImlhdCI6MTY5OTQxNDgyM30.lFJh8OZQZ7-ikeNXu-mMUCefWYH9fIpPPtMV4lvXl3s

###
POST  {{API_URL}}/dashboard/gate-in-out
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "gate_in_type":"in",
    "challan_type":"finishing"
}





