@API_URL = http://localhost:3000/pms/api/v1 
# @API_URL = http://192.168.1.160:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjMyODAsIkVtcElkIjoiY3dsMS1jaGVja2VyLTEiLCJVc2VyTmFtZSI6ImN3bDEtY2hlY2tlci0xIiwiVW5pdE5hbWUiOiJDV0wgVW5pdCAwMSIsIlVzZXJUeXBlIjoiV2FzaENoZWNrZWRCeSIsIlR5cGVOYW1lIjoiV2FzaENoZWNrZWRCeSIsIkNvbXBhbnlJZCI6MTcsIlVuaXRJZCI6Ijg3IiwiRnVsbE5hbWUiOiJjd2wxLWNoZWNrZXItMSIsIkxpbmVJZCI6bnVsbCwiSXNTZXdpbmciOm51bGwsIklzV2FzaGluZyI6dHJ1ZSwiSXNGaW5pc2hpbmciOm51bGwsImlhdCI6MTY5OTMzMzQxN30.mjeQ5uYh4ZOB-4XLzEj376jWDJfLcM9kikXn0GeIOKk

###
GET {{API_URL}}/wash-dashboard/all?date=2023-11-2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}

###
GET {{API_URL}}/wash-dashboard/weekly-receive-vs-delivery?unitId=87
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
    
}

###
GET {{API_URL}}/wash-dashboard/style-wise-receive-vs-delivery?unitId=87
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}

###
GET {{API_URL}}/wash-dashboard/total-received?unitId=87
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}

###
GET {{API_URL}}/wash-dashboard/total-delivery?unitId=87&&date=2023-10-23
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}

###
GET {{API_URL}}/wash-dashboard/rejection-percentage?unitId=87&&date=2023-10-28
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}

###
GET {{API_URL}}/wash-dashboard/total-production?unitId=87
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}

###
GET {{API_URL}}/wash-dashboard/this-month-total-production?unitId=87
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}

###
GET {{API_URL}}/wash-dashboard/wip?unitId=87
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    
}





